# Generated by Django 4.0 on 2021-12-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentform',
            name='Address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentform',
            name='Email_id',
            field=models.EmailField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='studentform',
            name='contact_number',
            field=models.IntegerField(null=True),
        ),
    ]
